name: 'Setup Python'
description: 'Setup Python environment by sourcing venv and installing requirements.txt'
inputs:
  requirements-file:
    description: 'Path to requirements.txt file'
    required: true
    default: './requirements.txt'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout actions'
      uses: 'actions/checkout@v3'
    - run: |
          cd ${{ github.workspace }}
          pip install virtualenv
          python3 -m venv .venv 
          source .venv/bin/activate
          pip install -r ${{ inputs.requirements-file }}
          cd -
      shell: bash